### ISSUE TITLE
NameError: name '_circ_thresh' is not defined

### ISSUE THREAD

**Issue by tolDK** [michaelorella/droppy#2]
When running this code - Found in the documentation:

`droppy "imgGS.jpg" --fitType bashforth-adams`

I get this error:

```
File "C:\Users\anaconda3\lib\site-packages\droppy\droppy.py", line 473, in main
    _circ_thresh, _lin_thresh, σ,

NameError: name '_circ_thresh' is not defined
```

Please let me know if I am doing something wrong or if this is a general issue. Thanks

**Comment by michaelorella** [comment]
Apologies for the delayed response, but this should be addressed by the previous commit. Let me know if there's anything else that is not working for you. Thanks!

**Comment by lgiesen** [comment]
FYI: I still have that error somehow 💭 
`!droppy '<PNG filepath>' -c 230 -l 170`
```/usr/local/lib/python3.10/dist-packages/droppy/edgedetection.py:3: UserWarning: viewer requires Qt
  from skimage.viewer import plugins
Analyzing <PNG filepath>
Traceback (most recent call last):
  File "/usr/local/bin/droppy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/droppy/droppy.py", line 473, in main
    _circ_thresh, _lin_thresh, σ,
NameError: name '_circ_thresh' is not defined. Did you mean: 'circ_thresh'?```
